"""First migration

Revision ID: c346efd55665
Revises: 
Create Date: 2022-09-10 11:28:38.101136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c346efd55665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemitem',
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['systemitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemitemhistory',
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['systemitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemitemhistory_date'), 'systemitemhistory', ['date'], unique=False)
    op.create_index(op.f('ix_systemitemhistory_item_id'), 'systemitemhistory', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_systemitemhistory_item_id'), table_name='systemitemhistory')
    op.drop_index(op.f('ix_systemitemhistory_date'), table_name='systemitemhistory')
    op.drop_table('systemitemhistory')
    op.drop_table('systemitem')
    # ### end Alembic commands ###
